version: "2.2"

services:
  jobmanager:
    image: flink:1.19.0
    container_name: "jobmanager"
    ports:
      - "8081:8081"
      - "8082:8082"
#    application 模式
#    command: standalone-job --job-classname com.job.ClassName [--job-id <job id>] [--jars /path/to/artifact1,/path/to/artifact2] [--fromSavepoint /path/to/savepoint] [--allowNonRestoredState] [job arguments]
#    session 模式
    command: jobmanager
    volumes:
      - flink-home:/opt/flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 16
        parallelism.default: 2

  taskmanager:
    image: flink:1.19.0
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 2
    volumes:
      - flink-home:/opt/flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 16
        parallelism.default: 2

volumes:
  flink-home: