version: "3.8"

services:
  filebeat:
    container_name: filebeat
    image: elastic/filebeat:8.5.3
    #depends_on:
    #  - elasticsearch
    #  - logstash
    #  - kibana
    command: filebeat -e -strict.perms=false
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/usr/share/filebeat/log