version: "3.8"

services:
  php:
    container_name: php
    build:
      context: ./image/74/
      dockerfile: Dockerfile
    image: fishep/php:7.4-fpm
#    image: php:7.4-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./www/project/:/var/www/project
