version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:1.28.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      - ./etc/nginx/ssl/:/etc/nginx/ssl/
      - ./www/project:/var/www/project