version: "3.8"

services:
  alpine:
    image: alpine:3.22.0
    container_name: alpine
#    ports:
#      - '1024:1024'
#      - '1025:1025'
    command: [ "sh", "-c", "while true; do sleep 3600; done" ]
#    networks:
#      default:
#      doris_net:
#
#networks:
#  default:
#  doris_net:
#    ipam:
#      config:
#        - subnet: 172.20.80.0/24